set(NG_MINGW_ROOT "$ENV{NG_MINGW_ROOT}" CACHE PATH "MinGW/w64devkit installation root")
if(NOT NG_MINGW_ROOT AND EXISTS "C:/raylib/w64devkit/bin/gcc.exe")
  set(NG_MINGW_ROOT "C:/raylib/w64devkit" CACHE PATH "MinGW/w64devkit installation root" FORCE)
endif()
if(NG_MINGW_ROOT)
  set(CMAKE_C_COMPILER "${NG_MINGW_ROOT}/bin/gcc.exe")
  set(CMAKE_CXX_COMPILER "${NG_MINGW_ROOT}/bin/g++.exe")
  set(CMAKE_RC_COMPILER "${NG_MINGW_ROOT}/bin/windres.exe")
  set(CMAKE_MAKE_PROGRAM "${NG_MINGW_ROOT}/bin/mingw32-make.exe" CACHE FILEPATH "MinGW make")
  # w64devkit needs its helper executables on PATH, including during later builds
  # started from an ordinary terminal or IDE.
  set(ENV{PATH} "${NG_MINGW_ROOT}/bin;$ENV{PATH}")
  string(REPLACE ";" "\\;" ng_compiler_path "$ENV{PATH}")
  set(ng_compiler_launcher "${CMAKE_COMMAND};-E;env;PATH=${ng_compiler_path}")
  set(CMAKE_C_COMPILER_LAUNCHER "${ng_compiler_launcher}")
  set(CMAKE_CXX_COMPILER_LAUNCHER "${ng_compiler_launcher}")
  set(CMAKE_C_LINKER_LAUNCHER "${ng_compiler_launcher}")
  set(CMAKE_CXX_LINKER_LAUNCHER "${ng_compiler_launcher}")
  list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES NG_MINGW_ROOT)
else()
  find_program(CMAKE_C_COMPILER NAMES gcc REQUIRED)
  find_program(CMAKE_CXX_COMPILER NAMES g++ REQUIRED)
  find_program(CMAKE_MAKE_PROGRAM NAMES mingw32-make REQUIRED)
endif()
